### ISSUE TITLE
path typecasting

### ISSUE THREAD

**Issue by kakoni** [hiroyuki-sato/embulk-parser-jsonpath#32]
I have json data that looks like this;
```
{
 "attributes": [{
          "attributeName": "Abbreviation",
          "attributeValue": ["Pt-ACTH-R1"]
        }, {
          "attributeName": "ShortName",
          "attributeValue": ["Pt-Adrenokortikotropiini-koe, lyhyt"]
        }, {
          "attributeName": "LongName",
          "attributeValue": ["Pt-Adrenokortikotropiini-koe, lyhyt"]
        }, {
          "attributeName": "Erikoisala",
          "attributeValue": ["K"]
        }, {
          "attributeName": "Langt_namn",
          "attributeValue": ["Pt-Adrenokortikotropin-test, kort"]
        }, {
          "attributeName": "Yksikko",
          "attributeValue": ["Lomake"]
        }]
}
```

I wish to get attribate name/value pairs into columns;

```
    columns:
      - {name: "abreviation", type: string, path: "$.attributes[?(@.attributeName== 'Abbreviation')].attributeValue[0]"}
```

This almost works ok, but gives me string value that has brackets;
``` 
["Pt-ACTH-R1"]
``` 

Wonder if there is a away to extract just the string value?

**Comment by hiroyuki-sato** [comment]
I'm the maintainer of this plugin, but I'm not familiar JSONPath 😄 

Have you ever tried the following?

```yaml
in:
  type: file
  path_prefix: ./test.txt
  parser:
    type: jsonpath
    columns:
    - {name: "abreviation", type: string, path: "$.attributeValue[0]"}
    root: "$.attributes[?(@.attributeName== 'Abbreviation')]"
out:
  type: stdout
```

`embulk  preview` shows the following output.

```
+--------------------+
| abreviation:string |
+--------------------+
|         Pt-ACTH-R1 |
+--------------------+
```
